version: '3.7'

services:
  climbing-day-member:
    image: seongolee/climbing-day-member:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0 # mysql 이미지
    ports:
      - "3306:3306" # TCP 포트 : 데이터베이스 연결 포트
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

