version: '3.7'

services:
  mysql-db:
    image: mysql:8.0 # mysql 이미지
    ports:
      - "3306:3306" # TCP 포트 : 데이터베이스 연결 포트
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      # MySQL 설정
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/initdb.d/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 15s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: seongolee/climbing-day-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - api-member

  api-mail:
    image: seongolee/climbing-day-mail:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  api-member:
    image: seongolee/climbing-day-member:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  api-center:
    image: seongolee/climbing-day-center:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy