version: '3.7'

services:
  mysql-db:
    image: mysql:8.0 # mysql 이미지
    ports:
      - "3306:3306" # TCP 포트 : 데이터베이스 연결 포트
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
