spring:
    config.activate.on-profile: dev

    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        properties:
            dialect: org.hibernate.dialect.MySQLDialect

    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
logging:
    level:
        org.hibernate:
            sql: debug