spring:
    config.activate.on-profile: dev

    datasource:
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: root
        password: 1234
        driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        properties:
            dialect: org.hibernate.dialect.OracleDialect

    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
logging:
    level:
        org.hibernate:
            sql: debug
