spring:
    application:
        name: api-gateway
    main:
        web-application-type: reactive              # 반응형 웹 어플리케이션 설정
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration        # 데이터베이스 관련 설정이 필요없으므로 비활성화 처리

    profiles:
        active: local

server:
    port: 8080
    servlet:
        context-path: /v1