openapi: 3.0.1
info:
  title: Climbing-day-member-swagger API Documentation
  description: Spring REST Docs with SwaggerUI
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /v1/admin/member:
    get:
      tags:
      - v1
      operationId: 일반회원 조회(어드민) API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-admin-member1631054700'
              examples:
                일반회원 조회(어드민) API:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":[{\"\
                    id\":1,\"email\":\"test@naver.com\",\"status\":\"PENDING\",\"\
                    roles\":\"ROLE_USER\"}]}"
  /v1/member/login:
    post:
      tags:
      - v1
      operationId: 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1-member-login965174184'
            examples:
              로그인 API:
                value: "{\"email\":\"test@naver.com\",\"password\":\"123456\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-member-login1698192666'
              examples:
                로그인 API:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MTY5MDE3MjAsImV4cCI6MTcxNjkwMzUyMCwicm9sZXMiOiJST0xFX1VTRVIifQ.cHbdOfyuPsfKjbKaCCBXNLrB_gNeccbTwh03drwJjSuCzAr6Fn2NUfKtLeYtOGwuUyV-4WXQxsgWpZ9A9xNBug\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MTY5MDE3MjAsImV4cCI6MTcxNjk2MTcyMCwicm9sZXMiOiJST0xFX1VTRVIifQ.G6dzqZdWmXkaXbXAfqlZqBV8VtN7aGtJrYDsIVYbChsZRhXOHERt53zhekmTLqeliKIfkaOQgkBofbX8INNB2w\"\
                    }}"
  /v1/member/register:
    post:
      tags:
      - v1
      operationId: 회원 가입 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1-member-register389488942'
            examples:
              회원 가입 API:
                value: "{\"email\":\"test@naver.com\",\"name\":\"test\",\"password\"\
                  :\"123456\",\"passwordConfirm\":\"123456\",\"phoneNumber\":\"010-1234-5678\"\
                  ,\"birthDate\":\"2000-11-11\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-member-register1233141654'
              examples:
                회원 가입 API:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
components:
  schemas:
    v1-member-login1698192666:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            accessToken:
              type: string
              description: 액세스 토큰
            refreshToken:
              type: string
              description: 리프래쉬 토큰
        message:
          type: string
          description: 상태 메시지
    v1-member-register1233141654:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 아이디 고유번호
        message:
          type: string
          description: 상태 메시지
    v1-member-register389488942:
      type: object
      properties:
        password:
          type: string
          description: 패스워드
        phoneNumber:
          type: string
          description: 핸드폰 번호
        passwordConfirm:
          type: string
          description: 패스워드 확인
        name:
          type: string
          description: 이름
        birthDate:
          type: string
          description: 생년월일
        email:
          type: string
          description: 이메일(계정)
    v1-admin-member1631054700:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: array
          items:
            type: object
            properties:
              roles:
                type: string
                description: 회원 권한
              id:
                type: number
                description: 회원 번호
              email:
                type: string
                description: 회원 이메일(계정)
              status:
                type: string
                description: 회원 상태
        message:
          type: string
          description: 상태 메시지
    v1-member-login965174184:
      type: object
      properties:
        password:
          type: string
          description: 패스워드
        email:
          type: string
          description: 이메일(계정)
