openapi: 3.0.1
info:
  title: Climbing-day-member-swagger API Documentation
  description: Spring REST Docs with SwaggerUI
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /v1/center:
    get:
      tags:
      - 암장 API
      summary: 모든 암장 조회
      description: 모든 암장 조회
      operationId: '암장 조회 API - '
      parameters:
      - name: page
        in: query
        description: 조회할 페이지 번호
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center1117171008'
              examples:
                암장 조회 API - 성공:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"content\"\
                    :[{\"id\":1,\"name\":\"????\",\"phoneNum\":\"02-111-1111\",\"\
                    address\":\"????\",\"latitude\":111.2222,\"longitude\":111.2222,\"\
                    openTime\":\"0:0\",\"closeTime\":\"23:59\",\"description\":\"\
                    ??\",\"notice\":\"??\",\"profileImage\":\"https://climbing-day-bucket.s3.ap-northeast-2.amazonaws.com/climbing-day-no-image.jpg\"\
                    ,\"memberNickName\":\"admin\"}],\"pageable\":{\"pageNumber\":0,\"\
                    pageSize\":10,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\"\
                    :false},\"offset\":0,\"paged\":true,\"unpaged\":false},\"last\"\
                    :true,\"totalPages\":1,\"totalElements\":1,\"number\":0,\"size\"\
                    :10,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\":false},\"\
                    first\":true,\"numberOfElements\":1,\"empty\":false}}"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center-44175865'
              examples:
                '암장 조회 API - 실패: Parameter 누락':
                  value: "{\"errorCode\":400,\"errorMessage\":\"파라미터 값이 정상적이지 않습니다\
                    . 확인 후 다시 시도해주세요.\",\"missingParams\":{\"page\":\"page 값이 확인되지\
                    \ 않습니다.\"}}"
  /v1/center/register:
    post:
      tags:
      - 암장 API
      summary: 암장 등록
      description: 암장 등록
      operationId: '암장 등록 API - '
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center-register-2054154011'
              examples:
                암장 등록 API - 성공:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center-centerName-946372771'
              examples:
                '암장 등록 API - 실패: 중복 암장이름':
                  value: "{\"errorCode\":409,\"errorMessage\":\"이미 암장이름입니다.\"}"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center-register-1534697879'
              examples:
                '암장 등록 API - 실패: 필드 유효성':
                  value: "{\"errorCode\":400,\"errorMessage\":\"입력값에 대한 검증에 실패했습니다\
                    .\",\"validation\":{\"address\":\"주소는 필수 항목입니다.\",\"name\":\"암\
                    장이름은 필수 항목입니다.\",\"phoneNum\":\"전화번호는 필수 항목입니다.\"}}"
      security:
      - bearerAuthJWT: []
  /v1/center/{centerName}:
    get:
      tags:
      - 암장 API
      summary: 암장 조회(이름)
      description: 암장 조회(이름)
      operationId: "암장 조회 API - 실패: 존재하지 않는 암장"
      parameters:
      - name: centerName
        in: path
        description: 암장 이름
        required: true
        schema:
          type: string
      responses:
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1-center-centerName-946372771'
              examples:
                '암장 조회 API - 실패: 존재하지 않는 암장':
                  value: "{\"errorCode\":400,\"errorMessage\":\"존재하지 않는 암장입니다.\"}"
components:
  schemas:
    v1-center-register-2054154011:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 암장 고유번호
        message:
          type: string
          description: 상태 메시지
    v1-center1117171008:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          description: "암장 정보, 페이징 정보"
        message:
          type: string
          description: 상태 메시지
    v1-center-centerName-946372771:
      type: object
      properties:
        errorMessage:
          type: string
          description: 상태 메시지
        errorCode:
          type: number
          description: 상태 코드
    v1-center-44175865:
      type: object
      properties:
        errorMessage:
          type: string
          description: 상태 메시지
        missingParams:
          type: object
          description: 누락된 파라미터
        errorCode:
          type: number
          description: 상태 코드
    v1-center-register-1534697879:
      type: object
      properties:
        errorMessage:
          type: string
          description: 상태 메시지
        errorCode:
          type: number
          description: 상태 코드
        validation:
          type: object
          description: 유효하지 않은 필드
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
