name: Build and Push Docker Images

# dev 브랜치 push action
on:
    push:
        branches:
            - dev
env:
    CURRENT_VERSION: "0.1.0"

jobs:
    build-image-and-push:
        runs-on: ubuntu-latest
        # 권한을 read로 제한
        permissions:
            contents: read
            # jdk 21 설정
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: "21"
                    distribution: "temurin"
            # gradle 설정
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3.1.0
            # gradle build, active dev
            -   name: Build with Gradle
                run: |
                    ./gradlew -p api/member build
            # 멀티플랫폼 이미지 빌드 환경 설정
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            # 멀티플랫폼 이미지 빌드 환경 설정
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            # dockerhub 에 로그인
            -   name: Login to Docker Hub
                run: |
                    echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            # Build and Push Docker Image
            # api/member
            -   name: member api > Build and Push Docker images
                uses: docker/build-push-action@v5
                with:
                    context: api/member
                    file: api/member/Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ${{ secrets.DOCKER_USERNAME }}/climbing-day-member:latest
